sudo: false
language: python
before_install:
- openssl aes-256-cbc -K $encrypted_9d61a4057135_key -iv $encrypted_9d61a4057135_iv -in baskobot-b8cae21c879b.json.enc -out baskobot-b8cae21c879b.json -d
install:
- curl https://www.googleapis.com/download/storage/v1/b/appengine-sdks/o/featured%2Fgoogle_appengine_1.9.80.zip\?generation\=1541715418368019\&alt\=media --output gcloud.zip
- unzip -q gcloud.zip
- pwd
script:
- pip install nosegae
- nosetests --with-gae --gae-lib-root ./google_appengine
deploy:
  provider: gae
  keyfile: baskobot-b8cae21c879b.json
  project: baskobot
  on: 
    branch: master
